namespace Framework.Constants.ItemSettings
{
    public enum InventoryResult
    {
        EQUIP_ERR_OK                                           = 0,
        EQUIP_ERR_CANT_EQUIP_LEVEL_I                           = 1,  // You must reach level %d to use that item.
        EQUIP_ERR_CANT_EQUIP_SKILL                             = 2,  // You aren't skilled enough to use that item.
        EQUIP_ERR_WRONG_SLOT                                   = 3,  // That item does not go in that slot.
        EQUIP_ERR_BAG_FULL                                     = 4,  // That bag is full.
        EQUIP_ERR_BAG_IN_BAG                                   = 5,  // Can't put non-empty bags in other bags.
        EQUIP_ERR_TRADE_EQUIPPED_BAG                           = 6,  // You can't trade equipped bags.
        EQUIP_ERR_AMMO_ONLY                                    = 7,  // Only ammo can go there.
        EQUIP_ERR_PROFICIENCY_NEEDED                           = 8,  // You do not have the required proficiency for that item.
        EQUIP_ERR_NO_SLOT_AVAILABLE                            = 9,  // No equipment slot is available for that item.
        EQUIP_ERR_CANT_EQUIP_EVER                              = 10, // You can never use that item.
        EQUIP_ERR_CANT_EQUIP_EVER_2                            = 11, // You can never use that item.
        EQUIP_ERR_NO_SLOT_AVAILABLE_2                          = 12, // No equipment slot is available for that item.
        EQUIP_ERR_2HANDED_EQUIPPED                             = 13, // Cannot equip that with a two-handed weapon.
        EQUIP_ERR_2HSKILLNOTFOUND                              = 14, // You cannot dual-wield
        EQUIP_ERR_WRONG_BAG_TYPE                               = 15, // That item doesn't go in that container.
        EQUIP_ERR_WRONG_BAG_TYPE_2                             = 16, // That item doesn't go in that container.
        EQUIP_ERR_ITEM_MAX_COUNT                               = 17, // You can't carry any more of those items.
        EQUIP_ERR_NO_SLOT_AVAILABLE_3                          = 18, // No equipment slot is available for that item.
        EQUIP_ERR_CANT_STACK                                   = 19, // This item cannot stack.
        EQUIP_ERR_NOT_EQUIPPABLE                               = 20, // This item cannot be equipped.
        EQUIP_ERR_CANT_SWAP                                    = 21, // These items can't be swapped.
        EQUIP_ERR_SLOT_EMPTY                                   = 22, // That slot is empty.
        EQUIP_ERR_ITEM_NOT_FOUND                               = 23, // The item was not found.
        EQUIP_ERR_DROP_BOUND_ITEM                              = 24, // You can't drop a soulbound item.
        EQUIP_ERR_OUT_OF_RANGE                                 = 25, // Out of range.
        EQUIP_ERR_TOO_FEW_TO_SPLIT                             = 26, // Tried to split more than number in stack.
        EQUIP_ERR_SPLIT_FAILED                                 = 27, // Couldn't split those items.
        EQUIP_ERR_SPELL_FAILED_REAGENTS_GENERIC                = 28, // Missing reagent
        EQUIP_ERR_NOT_ENOUGH_MONEY                             = 29, // You don't have enough money.
        EQUIP_ERR_NOT_A_BAG                                    = 30, // Not a bag.
        EQUIP_ERR_DESTROY_NONEMPTY_BAG                         = 31, // You can only do that with empty bags.
        EQUIP_ERR_NOT_OWNER                                    = 32, // You don't own that item.
        EQUIP_ERR_ONLY_ONE_QUIVER                              = 33, // You can only equip one quiver.
        EQUIP_ERR_NO_BANK_SLOT                                 = 34, // You must purchase that bag slot first
        EQUIP_ERR_NO_BANK_HERE                                 = 35, // You are too far away from a bank.
        EQUIP_ERR_ITEM_LOCKED                                  = 36, // Item is locked.
        EQUIP_ERR_GENERIC_STUNNED                              = 37, // You are stunned
        EQUIP_ERR_PLAYER_DEAD                                  = 38, // You can't do that when you're dead.
        EQUIP_ERR_CLIENT_LOCKED_OUT                            = 39, // You can't do that right now.
        EQUIP_ERR_INTERNAL_BAG_ERROR                           = 40, // Internal Bag Error
        EQUIP_ERR_ONLY_ONE_BOLT                                = 41, // You can only equip one quiver.
        EQUIP_ERR_ONLY_ONE_AMMO                                = 42, // You can only equip one ammo pouch.
        EQUIP_ERR_CANT_WRAP_STACKABLE                          = 43, // Stackable items can't be wrapped.
        EQUIP_ERR_CANT_WRAP_EQUIPPED                           = 44, // Equipped items can't be wrapped.
        EQUIP_ERR_CANT_WRAP_WRAPPED                            = 45, // Wrapped items can't be wrapped.
        EQUIP_ERR_CANT_WRAP_BOUND                              = 46, // Bound items can't be wrapped.
        EQUIP_ERR_CANT_WRAP_UNIQUE                             = 47, // Unique items can't be wrapped.
        EQUIP_ERR_CANT_WRAP_BAGS                               = 48, // Bags can't be wrapped.
        EQUIP_ERR_LOOT_GONE                                    = 49, // Already looted
        EQUIP_ERR_INV_FULL                                     = 50, // Inventory is full.
        EQUIP_ERR_BANK_FULL                                    = 51, // Your bank is full
        EQUIP_ERR_VENDOR_SOLD_OUT                              = 52, // That item is currently sold out.
        EQUIP_ERR_BAG_FULL_2                                   = 53, // That bag is full.
        EQUIP_ERR_ITEM_NOT_FOUND_2                             = 54, // The item was not found.
        EQUIP_ERR_CANT_STACK_2                                 = 55, // This item cannot stack.
        EQUIP_ERR_BAG_FULL_3                                   = 56, // That bag is full.
        EQUIP_ERR_VENDOR_SOLD_OUT_2                            = 57, // That item is currently sold out.
        EQUIP_ERR_OBJECT_IS_BUSY                               = 58, // That object is busy.
        EQUIP_ERR_CANT_BE_DISENCHANTED                         = 59,
        EQUIP_ERR_NOT_IN_COMBAT                                = 60, // You can't do that while in combat
        EQUIP_ERR_NOT_WHILE_DISARMED                           = 61, // You can't do that while disarmed
        EQUIP_ERR_BAG_FULL_4                                   = 62, // That bag is full.
        EQUIP_ERR_CANT_EQUIP_RANK                              = 63, // You don't have the required rank for that item
        EQUIP_ERR_CANT_EQUIP_REPUTATION                        = 64, // You don't have the required reputation for that item
        EQUIP_ERR_TOO_MANY_SPECIAL_BAGS                        = 65, // You cannot equip another bag of that type
        EQUIP_ERR_LOOT_CANT_LOOT_THAT_NOW                      = 66, // You can't loot that item now.
        EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE                       = 67, // You cannot equip more than one of those.
        EQUIP_ERR_VENDOR_MISSING_TURNINS                       = 68, // You do not have the required items for that purchase
        EQUIP_ERR_NOT_ENOUGH_HONOR_POINTS                      = 69, // You don't have enough honor points
        EQUIP_ERR_NOT_ENOUGH_ARENA_POINTS                      = 70, // You don't have enough arena points
        EQUIP_ERR_ITEM_MAX_COUNT_SOCKETED                      = 71, // You have the maximum number of those gems in your inventory or socketed into items.
        EQUIP_ERR_MAIL_BOUND_ITEM                              = 72, // You can't mail soulbound items.
        EQUIP_ERR_INTERNAL_BAG_ERROR_2                         = 73, // Internal Bag Error
        EQUIP_ERR_BAG_FULL_5                                   = 74, // That bag is full.
        EQUIP_ERR_ITEM_MAX_COUNT_EQUIPPED_SOCKETED             = 75, // You have the maximum number of those gems socketed into equipped items.
        EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED              = 76, // You cannot socket more than one of those gems into a single item.
        EQUIP_ERR_TOO_MUCH_GOLD                                = 77, // At gold limit
        EQUIP_ERR_NOT_DURING_ARENA_MATCH                       = 78, // You can't do that while in an arena match
        EQUIP_ERR_TRADE_BOUND_ITEM                             = 79, // You can't trade a soulbound item.
        EQUIP_ERR_CANT_EQUIP_RATING                            = 80, // You don't have the personal, team, or battleground rating required to buy that item
        EQUIP_ERR_NO_OUTPUT                                    = 81,
        EQUIP_ERR_NOT_SAME_ACCOUNT                             = 82, // Account-bound items can only be given to your own characters.
        EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_COUNT_EXCEEDED_IS    = 84, // You can only carry %d %s
        EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_SOCKETED_EXCEEDED_IS = 85, // You can only equip %d |4item:items in the %s category
        EQUIP_ERR_SCALING_STAT_ITEM_LEVEL_EXCEEDED             = 86, // Your level is too high to use that item
        EQUIP_ERR_PURCHASE_LEVEL_TOO_LOW                       = 87, // You must reach level %d to purchase that item.
        EQUIP_ERR_CANT_EQUIP_NEED_TALENT                       = 88, // You do not have the required talent to equip that.
        EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_EQUIPPED_EXCEEDED_IS = 89, // You can only equip %d |4item:items in the %s category
        EQUIP_ERR_SHAPESHIFT_FORM_CANNOT_EQUIP                 = 90, // Cannot equip item in this form
        EQUIP_ERR_ITEM_INVENTORY_FULL_SATCHEL                  = 91, // Your inventory is full. Your satchel has been delivered to your mailbox.
        EQUIP_ERR_SCALING_STAT_ITEM_LEVEL_TOO_LOW              = 92, // Your level is too low to use that item
        EQUIP_ERR_CANT_BUY_QUANTITY                            = 93, // You can't buy the specified quantity of that item.
    };
}
